# Generated by Django 5.0.7 on 2024-07-30 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='genger',
            new_name='gender',
        ),
    ]
