# Generated by Django 5.0.7 on 2024-07-30 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_genger_staff_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='adress',
            new_name='address',
        ),
    ]
