# Generated by Django 5.0.7 on 2024-07-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject',
        ),
    ]
