# Generated by Django 5.0.7 on 2024-07-31 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_course_updated_at_alter_staff_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_year',
            name='end_session',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session_year',
            name='start_session',
            field=models.DateField(),
        ),
    ]
