# Generated by Django 5.0.7 on 2024-07-31 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_session_year_end_session_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='session_id',
        ),
    ]
