# Generated by Django 5.0.7 on 2024-07-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_student_session_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
