# Generated by Django 5.0.7 on 2024-08-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_studentnotification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentnotification',
            old_name='stdent_id',
            new_name='student_id',
        ),
    ]
