# Generated by Django 5.0.7 on 2024-08-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_attandance_attendance_report'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attandance',
            new_name='Attendance',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='attandance_date',
            new_name='attendance_date',
        ),
    ]
