# Generated by Django 5.0.7 on 2024-08-05 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_attandance_attendance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_report',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attendance'),
        ),
    ]
