# Generated by Django 5.0.7 on 2024-08-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_driver_tranprot_notice_transport'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tranprot_Notice',
            new_name='Transprot_Notice',
        ),
    ]
