# Generated by Django 5.0.7 on 2024-08-11 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_rename_tranprot_notice_transprot_notice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transprot_Notice',
            new_name='Transport_Notice',
        ),
    ]
