# Generated by Django 5.0.7 on 2024-08-11 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_rename_transprot_notice_transport_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='driver_name',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
