# Generated by Django 5.0.7 on 2024-08-11 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_driver_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='address',
            field=models.TextField(),
        ),
    ]
