# Generated by Django 5.0.7 on 2024-08-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_driver_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='driver_name',
            field=models.CharField(max_length=100),
        ),
    ]
