# Generated by Django 5.0.7 on 2024-08-12 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_transport_driver_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
