# Generated by Django 5.0.7 on 2024-08-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_assignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='submittion_last_date',
            new_name='submission_last_date',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='submittion_last_time',
            new_name='submission_last_time',
        ),
    ]
