# Generated by Django 5.0.7 on 2024-08-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_rename_submittion_last_date_assignment_submission_last_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='staff_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='assignment',
            name='session_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
