# Generated by Django 5.0.7 on 2024-08-24 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_remove_assignment_staff_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='submission_last_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='submission_last_time',
        ),
    ]
