# Generated by Django 5.0.7 on 2024-08-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_remove_assignment_submission_last_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_last_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='submission_last_time',
            field=models.TimeField(null=True),
        ),
    ]
