# Generated by Django 5.0.7 on 2024-08-25 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_assignment_submission_last_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='session_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.session_year'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
    ]
